# Generated by Django 3.2.4 on 2021-06-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='commpleted',
            new_name='completed',
        ),
    ]
